package Oasis_tasks;

import java.util.*;


public class Game1 {

    static int Random() {
        int number = (int)(Math.random()*(100-1+1)+1);
        return number ;
    }


    public static void main (String args[]) {

        Scanner sc = new Scanner(System.in);

        System.out.println("************Welcome to the NUMBER GUESSING game**************\n");
        System.out.println("Hello I am Sahil Sengra your guide in this game\n ");

        System.out.println("Game Details:");
        System.out.println("1. You have to guess the number in least possible attempts");
        System.out.println("2. The lesser the number of attempts the better your performance ");
        System.out.println("3. You will get a score based on the number of attempts taken ");


        int round = 0;

        System.out.println("\nSet the number of attempts in which you would like to complete this game  :");
        int tries = sc.nextInt();

        int count = 1;


        while(true){

            System.out.println("\n**************** ROUND "+(round+ 1)+"****************");
            int ComNum = Random();
            System.out.println("Guess the number generated by the computer.....\n");

            for(int i =0 ; i < tries ; i++) {

                System.out.println("Attempt Number :" + count );
                int UserNum = sc.nextInt();

                if (UserNum == ComNum) {
                    System.out.println("Congratulations you have guessed the number correctly\n");
                    System.out.println("Game Statistics:");
                    System.out.println("Number of attempts taken = "+count);
                    System.out.println("Your Score is = "+(100/count)*2);
                    System.out.println("\n**********Round "+(round + 1)+" has ended***********\n");
                    break;
                }
                else if (UserNum >= ComNum) {
                    System.out.println("Try guessing a smaller number\n");
                }
                else if (UserNum <= ComNum) {
                    System.out.println("Try guessing a higher number\n");
                }

                count++;


            }

            if(count>tries)
                System.out.println("Number of attempts exceeded....\nBetter Luck Next Time \nScore = 0 ");
            System.out.println("Would you like to play again\nEnter 1 for yes and 0 for no");
            int choice = sc.nextInt();
            if(choice == 0)
                break;
            round++;
            count = 1;

        }

        System.out.println("\n****************Thank You for Playing******************** ");
        System.out.println("\n****************THE END******************** ");




    }

}
